"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { 
    Play, 
    SkipForward, 
    Shuffle, 
    Coffee, 
    Phone, 
    CheckCircle2,
    Circle,
    Clock,
    Inbox,
    AlertTriangle,
    Battery,
    BatteryMedium,
    Zap
} from "lucide-react";
import { cn } from "@/lib/utils";

interface DayPlanProps {
    energy: "low" | "medium" | "high";
    hours: number;
}

// Mock data - will be generated by Claude based on energy/hours
const generatePlan = (energy: string, hours: number) => {
    const blockDuration = energy === "low" ? 25 : energy === "medium" ? 45 : 60;
    const breakDuration = energy === "low" ? 10 : energy === "medium" ? 5 : 5;
    
    return {
        currentTask: {
            id: "1",
            title: "Revisar propuesta cliente ABC",
            project: "Cliente ABC",
            projectColor: "#4F6BFF",
            duration: 45,
            priority: "high",
            miniSteps: [
                { id: "1a", text: "Abrir documento en Drive", done: false },
                { id: "1b", text: "Leer sección de precios", done: false },
                { id: "1c", text: "Anotar 3 dudas principales", done: false },
                { id: "1d", text: "Enviar feedback al equipo", done: false },
            ],
        },
        schedule: [
            { time: "09:00", task: "Revisar propuesta cliente", type: "work", duration: 45 },
            { time: "09:45", task: "Micro-descanso", type: "break", duration: 5, icon: Coffee },
            { time: "09:50", task: "Preparar para reunión", type: "work", duration: 10 },
            { time: "10:00", task: "Daily Standup", type: "meeting", duration: 30, icon: Phone },
            { time: "10:30", task: "Responder emails urgentes", type: "work", duration: 45 },
            { time: "11:15", task: "Descanso largo", type: "break", duration: 10, icon: Coffee },
            { time: "11:25", task: "Procesar inbox", type: "work", duration: 35 },
        ],
        stats: {
            totalWorkMinutes: hours * 60,
            remainingMinutes: hours * 60,
            nextMeeting: "45 min",
            inboxCount: 5,
            alertsCount: 2,
        },
    };
};

export function DayPlan({ energy, hours }: DayPlanProps) {
    const plan = generatePlan(energy, hours);
    const [miniSteps, setMiniSteps] = useState(plan.currentTask.miniSteps);
    const [currentIndex, setCurrentIndex] = useState(0);

    const toggleStep = (id: string) => {
        setMiniSteps(steps =>
            steps.map(s => s.id === id ? { ...s, done: !s.done } : s)
        );
    };

    const completedSteps = miniSteps.filter(s => s.done).length;
    const progress = (completedSteps / miniSteps.length) * 100;

    const energyIcon = energy === "low" ? Battery : energy === "medium" ? BatteryMedium : Zap;
    const energyLabel = energy === "low" ? "Baja" : energy === "medium" ? "Media" : "Alta";
    const energyColor = energy === "low" ? "text-coral" : energy === "medium" ? "text-yellow-500" : "text-mint";

    return (
        <div className="space-y-6">
            {/* Top Status Bar */}
            <div className="flex flex-wrap items-center gap-3 p-4 rounded-2xl bg-muted/50">
                <div className={cn("flex items-center gap-2 px-3 py-1.5 rounded-full bg-background", energyColor)}>
                    {energyIcon && <motion.div><Battery className="h-4 w-4" /></motion.div>}
                    <span className="text-sm font-medium">Energía {energyLabel}</span>
                </div>
                <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-background">
                    <Clock className="h-4 w-4 text-muted-foreground" />
                    <span className="text-sm">{hours}h restantes</span>
                </div>
                <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-background">
                    <Phone className="h-4 w-4 text-primary" />
                    <span className="text-sm">Próxima reunión: {plan.stats.nextMeeting}</span>
                </div>
                <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-background ml-auto">
                    <Inbox className="h-4 w-4 text-purple" />
                    <span className="text-sm">{plan.stats.inboxCount} inbox</span>
                </div>
                {plan.stats.alertsCount > 0 && (
                    <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-coral/10 text-coral">
                        <AlertTriangle className="h-4 w-4" />
                        <span className="text-sm">{plan.stats.alertsCount} alertas</span>
                    </div>
                )}
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Main: Current Task */}
                <div className="lg:col-span-2 space-y-4">
                    {/* Current Task Card */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="p-6 rounded-2xl border-2 border-primary/20 bg-primary/5"
                    >
                        <div className="flex items-center gap-2 mb-2">
                            <span className="text-xs font-medium text-primary uppercase tracking-wide">🎯 Ahora</span>
                        </div>
                        
                        <h2 className="text-xl font-bold mb-3">{plan.currentTask.title}</h2>
                        
                        <div className="flex items-center gap-3 mb-4">
                            <span 
                                className="px-2 py-1 rounded-lg text-xs font-medium"
                                style={{ backgroundColor: `${plan.currentTask.projectColor}20`, color: plan.currentTask.projectColor }}
                            >
                                {plan.currentTask.project}
                            </span>
                            <span className="text-sm text-muted-foreground flex items-center gap-1">
                                <Clock className="h-3 w-3" />
                                {plan.currentTask.duration} min
                            </span>
                        </div>

                        {/* Progress bar */}
                        <div className="mb-4">
                            <div className="flex justify-between text-xs text-muted-foreground mb-1">
                                <span>Progreso</span>
                                <span>{completedSteps}/{miniSteps.length} pasos</span>
                            </div>
                            <div className="h-2 bg-muted rounded-full overflow-hidden">
                                <motion.div 
                                    className="h-full bg-primary rounded-full"
                                    initial={{ width: 0 }}
                                    animate={{ width: `${progress}%` }}
                                />
                            </div>
                        </div>

                        {/* Mini Steps */}
                        <div className="space-y-2 mb-6">
                            <p className="text-sm font-medium text-muted-foreground">Mini-pasos:</p>
                            {miniSteps.map((step) => (
                                <button
                                    key={step.id}
                                    onClick={() => toggleStep(step.id)}
                                    className={cn(
                                        "w-full flex items-center gap-3 p-3 rounded-xl text-left transition-all",
                                        step.done 
                                            ? "bg-mint/10 text-mint-dark line-through" 
                                            : "bg-background hover:bg-accent"
                                    )}
                                >
                                    {step.done ? (
                                        <CheckCircle2 className="h-5 w-5 text-mint flex-shrink-0" />
                                    ) : (
                                        <Circle className="h-5 w-5 text-muted-foreground flex-shrink-0" />
                                    )}
                                    <span className="text-sm">{step.text}</span>
                                </button>
                            ))}
                        </div>

                        {/* Action Buttons */}
                        <div className="flex gap-3">
                            <button className="flex-1 py-3 rounded-xl bg-primary text-white font-medium flex items-center justify-center gap-2 hover:bg-primary/90 transition-all">
                                <Play className="h-4 w-4" />
                                Iniciar Focus ({plan.currentTask.duration}min)
                            </button>
                            <button className="p-3 rounded-xl border border-border hover:bg-accent transition-all">
                                <SkipForward className="h-5 w-5" />
                            </button>
                            <button className="p-3 rounded-xl border border-border hover:bg-accent transition-all">
                                <Shuffle className="h-5 w-5" />
                            </button>
                        </div>
                    </motion.div>
                </div>

                {/* Sidebar: Schedule */}
                <div className="space-y-4">
                    <motion.div
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        className="p-4 rounded-2xl border border-border bg-background"
                    >
                        <h3 className="font-semibold mb-4">📅 Plan del día</h3>
                        <div className="space-y-1">
                            {plan.schedule.map((item, i) => (
                                <div 
                                    key={i}
                                    className={cn(
                                        "flex items-center gap-3 p-2 rounded-lg text-sm",
                                        i === currentIndex && "bg-primary/10",
                                        item.type === "break" && "text-muted-foreground"
                                    )}
                                >
                                    <span className="font-mono text-xs w-12">{item.time}</span>
                                    {item.type === "break" && <Coffee className="h-3 w-3" />}
                                    {item.type === "meeting" && <Phone className="h-3 w-3 text-primary" />}
                                    <span className={cn(
                                        "flex-1 truncate",
                                        item.type === "break" && "italic"
                                    )}>
                                        {item.task}
                                    </span>
                                    <span className="text-xs text-muted-foreground">{item.duration}m</span>
                                </div>
                            ))}
                        </div>
                    </motion.div>

                    {/* Quick Actions */}
                    <div className="grid grid-cols-2 gap-2">
                        <button className="p-3 rounded-xl border border-border hover:bg-accent transition-all text-sm font-medium flex items-center justify-center gap-2">
                            <Inbox className="h-4 w-4" />
                            Inbox
                        </button>
                        <button className="p-3 rounded-xl border border-coral/50 bg-coral/5 text-coral hover:bg-coral/10 transition-all text-sm font-medium flex items-center justify-center gap-2">
                            <AlertTriangle className="h-4 w-4" />
                            Alertas
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}
